In [1]:
import numpy as np

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
a1 = np.arange(2,51,3)
print(a1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
l1 = list(map(int,input().split()))
l2 = list(map(int,input().split()))
a1 = np.array(l1)
a2 = np.array(l2)
a3 = np.concatenate((a1,a2))
print("Array after Concatenation:",a3)
print("Sorted:",np.sort(a3))

 1 2 3 4 5 6 
9 8 7 6 5 4
Array after Concatenation: [1 2 3 4 5 6 9 8 7 6 5 4]
Sorted: [1 2 3 4 4 5 5 6 6 7 8 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
a1 = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

print(a1)

print("Dimension:",a1.ndim)

print("Size:",a1.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension: 2
Size: 12


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

Ans: To convert a 1D array into 2D array numpy functions can be used like expand_dims,newaxis and reshape. Given below are all the three implementations

In [6]:
a1 = np.arange(1,13)
print("Dimension of array 1:",a1.ndim)

a2 = np.expand_dims(a1, 1)
print("Dimension of Array 2:",a2.ndim)

a3 = a1[np.newaxis]
print("Dimension of Array 3:",a3.ndim)

a4 = a1.reshape(-1,2)
print("Dimension of Array 4:",a4.ndim)

Dimension of array 1: 1
Dimension of Array 2: 2
Dimension of Array 3: 2
Dimension of Array 4: 2


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [9]:
a1 = np.arange(1,10).reshape(3,3)
print("Array 1:")
print(a1)

a2 = np.arange(10,19).reshape(3,3)
print("Array 2:")
print(a2)

a3 = np.vstack((a1,a2))
print("Array 3(Vertical):")
print(a3)

a4 = np.hstack((a1,a2))
print("Array 4(Horizontal):")
print(a4)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Array 3(Vertical):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Array 4(Horizontal):
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# Questions 6:
How to get unique items and counts of unique items?

In [10]:
a1 = np.array([1,3,5,2,5,7,4,8,9,5,8,4,2,7,4])
un, un_c = np.unique(a1,return_counts=True)
print("Unique Elements:", un)
print("Unique Count:   ",un_c)

Unique Elements: [1 2 3 4 5 7 8 9]
Unique Count:    [1 2 1 3 3 2 2 1]
